### ISSUE TITLE
"Guide" pages for CMS open data

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1518]
Achim has prepared a set of useful instructions which could guide the users in use of the CMS Open Data, see 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSPublicData

The current contents of this page reflect the currents state of CODP. However, we would very much like to propagate these instructions to the new portal interface.
Would it be possible for you to prepare draft pages based on this material, we could call them "Guide to CMS Open Data" divided into "Guide to research use of CMS Open Data" and "Guide to education use of CMS Open Data"? As a first approximation, the contents can be taken as such (adding links), starting with

- "Guide to CMS Open Data" with what is under Header page in the page linked above.
- "Guide to education use of CMS Open Data" with what is under Education page
- "Guide to research use of CMS Open Data" with what is under Research page

@RaoOfPhysics Can you help with the text once it is in the record?

**Comment by katilp** [comment]
@daslerr @sefeg Would it be possible to move on with this? It will probably take us some time to review and iterate and it is important that this is in place for the release.

**Comment by sefeg** [comment]
It is part of the current sprint! 😄  @katilp

**Comment by katilp** [comment]
Will this be soon visible on dev? It should also be visible from a fixed link, i.e. from http://opendata-dev.web.cern.ch/about/cms

**Comment by sefeg** [comment]
Unless the current (shared) version needs any more urgent changes, we can soon upload it. The functionality for placing articles and images on the landing page is being implemented in this sprint.

**Comment by sefeg** [comment]
Current status: The guides are deployed on dev. I am working on updating the links. The current version of the articles can be found [here](http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data), [here](http://opendata-dev.web.cern.ch/articles/cms-guide-to-research-use-of-cms-open-data) and [here](http://opendata-dev.web.cern.ch/articles/cms-response-to-errors).

**Comment by katilp** [comment]
I've made a pull request with substantial changes to Guide to education use
https://github.com/cernopendata/opendata.cern.ch/pull/1767 so maybe avoid update before it is merged

**Comment by sefeg** [comment]
@katilp @RaoOfPhysics  Shall we close this issue, now that you both iterated over the guide pages?

**Comment by RaoOfPhysics** [comment]
We're still waiting for feedback from Achim, so can we leave this open for now?

**Comment by katilp** [comment]
Point from Achim:

- [ ] How will users be guided to this page?

- [ ] The link to how to install the virtualbox after "you will need to use the appropriate VMs" missing

- [ ] The link to "Start anlysing the data" points to 2010. The text states "choose 2010 or 2011" but no choice on that page.

- [ ] Check when the choice of whether one wants to go  for 2010 or 2011/12 already has to be made *before* going to  "start analysing the data"?

- [ ] Update the link to the dimuon analysis example (Option A) http://opendata-dev.web.cern.ch/record/5001

- [ ] Check links in In the "exploring the 2010 datasets" section

- [ ] Check the text cross references given in "I want to find out which 2010 dataset .... is most useful" 

- [ ] Check the link to the CMS event display should be http://opendata-dev.web.cern.ch/visualise/events/cms

- [ ] Check the "Trigger" link should be http://opendata-dev.web.cern.ch/articles/guide-to-the-cms-trigger-system

- [ ] Check that the "luminosity" link points to correct information (all years?)

- [ ] Check that validated runs (JSON) points to correct information (all years?)

**Comment by katilp** [comment]
Fixes for http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data

- [ ] The title and the link still has two times CMS

- [ ] visualise/events/CMS still does not (change to visualise/events/cms)

- [ ] events loading on the event display still does not work

- [ ] http://opendata-dev.web.cern.ch/articles/search?page=1&size=20&q=display&subtype=Derived&experiment=CMS for search for ig file search, remove articles from the path

- [ ] records 300 and 301 bring to cod2 portal, check the path

- [ ] remove the github link for the event display instructions, needs the record from #1789

- [ ] histogram visualizer link to cod2 (capital CMS ok for that on dev)

- [ ] NB http://opendata-dev.web.cern.ch/record/53# has file index part even if it does not have files

- [ ]  remove the link "using a limited number of CMS events that are suitable for this type of exercise", add see Instructions for use of CMS Open Data in spreadsheets for schools and education, needs records from #1760

- [ ] Analysing CMS Open Data in Jupyter using python needs the record from #1761 
 
- [ ] Analysing CMS Open Data in Jupyter using R needs the record from #1762 

- [ ] search http://opendata-dev.web.cern.ch/articles/search?page=1&size=20&q=&keywords=education&experiment=CMS does not work, remove articles from the path

- [ ] NB file name does not display in http://opendata-dev.web.cern.ch/record/50

- [ ]  "re-discover" the Higgs boson change year to 2011-2012 and the link to articles/cms-2011-virtual-machines-how-to-install

- [ ] change getting started link to articles/getting-started-with-cms-2011-open-data

**Comment by katilp** [comment]
Fixes for http://opendata-dev.web.cern.ch/articles/cms-guide-to-research-use-of-cms-open-data

- [ ] "a more sophisticated analysis using CMS Open Data" -> research-oriented analysis?

- [ ] add link to /articles/cms-guide-to-troubleshooting

- [ ] not sure if 2011-2012 data is more sophisticated, it is more "difficult" because of pile-up but the sophistication is more or less the same

- [ ] change link name " this Twiki page" to "public CMS luminosity information"

- [ ] move "on the virtual machine (separately for 2010 and 2011/2012 data)" from the title to the first item (the user wants the environment, which happens to be a virtual machine, but this is not a choice of the user...)

- [ ] the approriate VM -> appropriate 

- [ ] add direct links to VM in "Install the appropriate VM, 2010 VM for 2010 data, /record/250, and 2011 VM for 2011/2012 data. /record/255" 

- [ ] Go to "Getting started with CMS 2010 data" for 2010 or "Getting started with CMS 2011 data"  -> add open: CMS 201N open data", fix links to /articles/getting-started-with-cms-2010-open-data, /articles/getting-started-with-cms-2011-open-data

- [ ] move "(e.g. inclusive di-muon spectrum analysis example directly from AOD or two-/four-lepton analysis example with intermediate ntuples)." to the second item

- [ ] replace (simpler), (more sophisticated) with more concrete terms

- [ ] Remove "For 2011 option A, take the SingleMu or DoubleMu dataset index files from http://opendata.cern.ch/record/32 or http://opendata.cern.ch/record/17." now updated

- [ ] "Go to 2010 CMS derived datasets" add "of event display type"

- [ ] change ""I want an alternative way to view these event displays." to "or, alternatively"

- [ ] the topic list under  "I want to find out which 2010 dataset and/or analysis/validation example is most useful for my purpose."  is confusing, may want to rephrase

- [ ] cannot find new cod3 simulated dataset names, see #1888 

- [ ] "Go to 2011 CMS derived datasets" add "of event display type"

- [ ] Luminosity information and validated run records still missing (no changes need to the guide, they will appear in search), see #1864 for 2012 validated runs, and #1865 ? for 2012 lumi

- [ ] Under condition data:  "Getting started with CMS 2011 data"->  "Getting started with CMS 2011 open data" + fix link as above

- [ ] trigger example code, link will be under record but cannot find them yet #1300 (commit done but no PR?)

- [ ] fix formatting under     "I want to (re)validate the 2010 datasets within my setup…", and add direct links to records

**Comment by katilp** [comment]
Update to http://opendata-dev.web.cern.ch/articles/cms-guide-to-education-use-of-cms-open-data : 

We do not explicitly mention csv anywhere. In old portal we had
"For education purposes, the complex primary data need to be processed into a format (examples below) that is good for simple applications."

Add a mention on this as the last item in the list under "Make histograms with collision data".

- [ ] All applications mentioned above use open data in simplified csv format. See [all available csv datasets](/search?page=1&size=20&q=&type=Dataset&experiment=CMS&subtype=Derived&file_type=csv), which have been extracted directly from the original collision datasets.

- [ ]  If you are interested in producing your own selection of open data in csv format, see [example software ](/record/552) for the processing step.

**Comment by katilp** [comment]
Closed via #1924
