### ISSUE TITLE
CMS validation and example software records to be added

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1548]
Validation records to be added

- [x] jets (Matthias + additions from Sasha, the latter, i.e. the 'optimized' version, that should go to the portal) 
  - https://github.com/cms-opendata-validation/2011-jet-inclusivecrosssection-ntupleproduction-optimized see #1191 #1192 #1830
  - ~~https://github.com/cms-opendata-validation/2011-jet-inclusivecrosssection-analysis see #1192~~ needs work to run on Open data VM
- [x] ttbar (2011-minimumbias-doublemu-mueg-ttbar) from Sasha
  - https://github.com/cms-opendata-validation/2011-doubleelectron-doublemu-mueg-ttbar  see #1552 /record/5000
- [x] rereco and aod comparison see #1525 /record/463 and /record/464
- [x] trigger records see ~~#1510~~ #1300 
   - the text is rather "Guide" but they can "contain" or "point to" software records from
https://github.com/caredg/cms_legacy_data/tree/2010/TriggerInfo/TriggerInfoAnalyzer and https://github.com/caredg/cms_legacy_data/tree/2011/TriggerInfo/TriggerInfoAnalyzer
- [x] 2011 instruction for dimuon spectrum example see #1556 
   - https://github.com/qfuehring/OpenDataMuonExample or /afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo_2011 see #1556 /record/5001

Existing validation records to be cross-linked to the github area

- [x] http://opendata.cern.ch/record/462 to https://github.com/cms-opendata-validation/2010-minimumbias-trackvertex
- [x] http://opendata.cern.ch/record/461 to https://github.com/cms-opendata-validation/2010-commissioning-dimuon
- [x] http://opendata.cern.ch/record/460 to https://github.com/cms-opendata-validation/2010-mu-mumonitor-dimuon

**Comment by katilp** [comment]
Closed as implemented
