### ISSUE TITLE
CMS: Updates to the CMS research guide

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1994]
In http://opendata-dev.web.cern.ch/docs/cms-guide-to-research-use-of-cms-open-data

- [x] add (internal) after the "Rules of use... " link

- [x] "I want to produce some first physics  distributions" should read "I want to produce some example physics distributions" under "I want to find out which 2010 ...."

- [x] after Dedicated examples for 2011 beyond those available in add search link /search?page=1&size=20&q=&type=Software&subtype=Analysis&experiment=CMS&year=2011

- [x] Why big font in "choose a dataset, read the comments, and read also about simulated dataset names FIXME link"?

- [ ] simulated dataset link????? now in http://opendata-dev.web.cern.ch/about/cms-simulated-dataset-names will it stay  there or go to ../docs/...? #1888

- [ ] Glossary term behaviour (clicking bring to top) - separate item #1996

- [x] "Performing an analysis":
The MIT papers are given, but there is no link yet to their code 
repository (as promised in the heading)

- [x] "I want to (re)validate the 2010 datasets ..." change wording

- [ ] check the links for Go to [Validation software](/search?page=1&size=20&q=&type=Software&subtype=Validation&experiment=CMS) see #1956

**Comment by katilp** [comment]
Can be closed as the remaining items in the list are separate issues of their own
