### ISSUE TITLE
CMS: some fixes to general instruction flow

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2131]
Feedback from Achim

In http://opendata-dev.web.cern.ch/docs/cms-guide-for-research

- [x] Under "Exploring the 2011-2012 datasets": 
   "2011 CMS primary datasets" appears duplicate (the second should be
    changed to 2012)

- [x] The instructions on "I want to find out which 2011 dataset ..."
   should be udpated to include the 2011/12 Higgs example.

http://opendata-dev.web.cern.ch/docs/cms-virtual-machine-2011

- [x] "CMS VM Image, for 2011 CMS open data",
          "2011" should be replaced by "2011/12" throughout ?

- [x] should there be an introductory sentence stating that 
       the 2011 virtual machine is also good for 2012? 
       (or, easier: call it CMS 2011/2012 Virtual Machine?) 
 
- [x] should there be a cross reference to the 2010 virtual machine? 

- [x] 'scram b' generates a warning 
```
****WARNING: No need to export library once you have declared your library as plugin. 
          Please cleanup src/Demo/DemoAnalyzer/BuildFile by removing the <export></export> section.
```

          Should people be told to ignore the warning (since this is legacy code), 
          or should they be told to take action?

http://opendata-dev.web.cern.ch/record/252 and http://opendata-dev.web.cern.ch/record/250

- [ ] after the merge, check the subtitles #2103

- [ ] remove the double-links for errors #2171

http://opendata-dev.web.cern.ch/record/5001

- [x] check the updates from /afs/desy.de/user/g/geiser/public/CMS/opendata/MUO-10-004demo_2011  but see #2132

**Comment by katilp** [comment]
Closing as remaining items in #2103 and #2171
