### ISSUE TITLE
CMS: ML files for Tracking GPU studies from CMS Upgrade MC

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2459]
In connection with #2440, some ML samples will be produced from newly produced Upgrade samples and made available on the portal.

The datasets are produced and available:

/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/GEN-SIM-RAW
/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/GEN-SIM-RECO
/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/AODSIM

To do:

- [x] transfer the datasets above to eospublic 
  - request [done](https://cmsweb.cern.ch/phedex/prod/Request::View?request=1538866) completed
- [x] prepare the records for CODP for them
  - provenance in https://cms-pdmv.cern.ch/mcm/requests?prepid=PPD-RunIIAutumn18DR-00001&page=0&shown=127 see #2520
- [x] test that the ML file production workflow works on CMS Open Data VM
  -  the VM with encapsulated slc6 #2426 can be used (it is not yet on the portal record, NB two shells: 'CMS Shell' with SCL6 from the desktop, note the comment https://github.com/cernopendata/opendata.cern.ch/issues/2447#issuecomment-439849112 for `arch` )
  - GT 102X_upgrade2018_design_v9 is available  is available (note the changes needed to read the GT in the config file + symbolic links: cfr http://opendata.cern.ch/docs/cms-guide-for-condition-database)
- [x] prepare the CODP record for the ML file production workflow
   - have it in a github repo (see with @caredg )
   - provide the corresponding metadata for the CODP record (see #2589 )
- [x] produce the files and transfer to eospublic upload (see with @tiborsimko)
- [x] provide the metadata for the CODP records the ML files (see #2576)
- [ ] if appropriate, provide an example of usage as a software record

For contributions, see also https://github.com/cernopendata/opendata.cern.ch/wiki/Contributing-content-to-CERN-Open-Data

**Comment by AdrianoDee** [comment]
### Testing the ML production in the VM.

**VM:** CMS OpenData 1.4.0 from [here](https://cernbox.cern.ch/index.php/s/omF4JNCPMDigQk8)
**CMSSW:** 10_2_5 (production release for the dataset) and 10_3_5
**GT:** 102X_upgrade2018_design_v9
**SCRAM_ARCH**: slc7_am64_gcc700

NB: the VM seems to be listed as slc6 but when checking the OS I got

<img width="485" alt="schermata 2018-12-13 alle 11 27 40" src="https://user-images.githubusercontent.com/16901146/49932751-1c830e80-feca-11e8-9b0e-15802848a2d8.png">

Also cmsrel seems to be aware of that. The symlink has been set (in the directory I'm running)

`ln -sf /cvmfs/cms-opendata-conddb.cern.ch/102X_upgrade2018_design_v9.db 102X_upgrade2018_design_v9.db`

<img width="966" alt="schermata 2018-12-13 alle 11 53 09" src="https://user-images.githubusercontent.com/16901146/49934063-aa142d80-fecd-11e8-829a-cc911fb404e4.png">


1) Testing Generic RelVal Production 

Since the ML dataset production is run within the RECO step (step3), as first test I tried to run a generic RelVal workflow from the GEN step generating a config with cmsDriver

`cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi -n 10 --no_exec --eventcontent FEVTDEBUG -s GEN,SIM --datatier GEN-SIM --fileout file:step1.root --conditions 102X_upgrade2018_design_v9`

In the resulting config [*]  I've changed the GT following the guide

`#process.GlobalTag = GlobalTag(process.GlobalTag, '102X_upgrade2018_design_v9.db', '')`
`process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/102X_upgrade2018_design_v9.db')`
`process.GlobalTag.globaltag = '102X_upgrade2018_design_v9'
`
(it seems to have effect since before fixing I had a DB error)

The error I get:

<img width="828" alt="schermata 2018-12-13 alle 11 42 15" src="https://user-images.githubusercontent.com/16901146/49933530-26a60c80-fecc-11e8-9bb2-6ddfe1447d0e.png">

Full stack trace attached[*] . The module that has crashed is

`Module: Pythia8GeneratorFilter:generator (crashed)`

2) Testing RECO step on GEN-SIM-RAW files from the dataset

Basically I tried to run step3 config on one of the GEN-SIM-RAW dataset 

_/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIIAutumn18DR-PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/GEN-SIM-RAW_

accessed by eospublic

`eosfile = 'root://eospublic.cern.ch//eos/opendata/cms/MonteCarloUpgrade/RunIIAutumn18DR/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/GEN-SIM-RAW/PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/110000/09D95BE7-23C8-5542-9FA4-102E3FEDB7A2.root' `

again the config is one of the standard RelVal one generated with cmsDriver [*] 

`cmsDrivery.py step3 --conditions auto:phase1_2018_realistic -n -1 --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,VALIDATION --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --filein file:step2.root --fileout file:step3.root`

where the GT has been fixed as above and the input file too.

<img width="1212" alt="schermata 2018-12-13 alle 11 51 57" src="https://user-images.githubusercontent.com/16901146/49934005-80f39d00-fecd-11e8-8685-cc61aa3f9341.png">


-----------------------------------------------------------------------------------
I haven't tested the ML production config yet since it's based on the step3 config.

[*] https://cernbox.cern.ch/index.php/s/7oDx6LoNufndOwz

**Comment by katilp** [comment]
Thanks @AdrianoDee : note that the slc6 shell is available from the desktop icon (not from the icon at the bottom of the screem), and it is a singularity container with slc6. The native shell is indeed slc7.
This is on purpose (although we have to document it better!!) and all CMSSW specific command should be done on the slc6 shell. Sorry for the confusion.

**Comment by AdrianoDee** [comment]
Thanks @katilp, I'll check with slc6 and let you know soon

**Comment by AdrianoDee** [comment]
I just tested withe the slc6 within the CMS Shell (with SCRAM_ARC=slc6_am64_gcc700 ad CMSSW_10_2_5) and basically I'm getting the same errors.

**Comment by katilp** [comment]
OK, thanks, then it could be an error in the GT export. I understand that this runs with the same CMSSW and GT on lxplus. @ggovi could you please have a look (the error log in the cernbox link above)? Thanks!

**Comment by ggovi** [comment]
@katilp 
my check:
cd /cvmfs/cms-opendata-conddb.cern.ch
conddb --db 102X_upgrade2018_design_v9.db list 102X_upgrade2018_design_v9
# shows that the IdealGeometryRecord is there, mapped with tag TKRECO_Geometry_92YV3
conddb --db 102X_upgrade2018_design_v9.db list TKRECO_Geometry_92YV3
# shows the same iov content than the tag in production dB...
Looks everything in place - can't help much unfortunately...

**Comment by ggovi** [comment]
sorry for the big size text, is a bad result of a cut-and paste...

**Comment by AdrianoDee** [comment]
For completeness I just tested point 1) on lxplus and it's all smooth. For GT:

`process.genstepfilter.triggerConditions=cms.vstring("generation_step")`
`from Configuration.AlCa.GlobalTag import GlobalTag`
`process.GlobalTag = GlobalTag(process.GlobalTag, '102X_upgrade2018_design_v9', '')`

The result: 

<img width="832" alt="schermata 2018-12-13 alle 16 06 39" src="https://user-images.githubusercontent.com/16901146/49947266-1a807600-fef1-11e8-9a18-414d07765819.png">

**Comment by AdrianoDee** [comment]
Perfect, thanks! I'm checking how's working

**Comment by ggovi** [comment]
I've just realised that this GT has a built-in snapshot time. It is set to 2018-10-01 20:09:06, as you can see in:
https://cms-conddb-prod.cern.ch/cmsDbBrowser/search/Prod/102X_upgrade2018_design_v9
The file on CVMFS has been produced on October the 30, so it make sense that without overriding the snapshot time to it does not work. In the future, we could update the built-in snapshot time accordingly.

**Comment by AdrianoDee** [comment]
Hi, the fix with 

`process.GlobalTag.snapshotTime = cms.string("9999-12-31 23:59:59.000")`

is working for the RelVal standard sequences. Now I tried to run the ML production on the GEN-SIM-RAW dataset and I catch an error with the "l1conddb". In order, if I try to run the step2 on the data with a standard sequence such as

`step2 --conditions auto:phase1_2018_design --eventcontent FEVTDEBUGHLT -s` `DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2018 --datatier GEN-SIM-DIGI-RAW  --geometry` `DB:Extended `

I get an error such as

```
----- Begin Fatal Exception 17-Dec-2018 13:05:11 CET-----------------------
An exception of category 'Invalid DetId' occurred while
   [0] Processing  Event run: 1 lumi: 28 event: 55787 stream: 0
   [1] Running path 'digitisation_step'
   [2] Calling method for module MixingModule/'mix'
Exception Message:
Cannot initialize HcalDetId from 10000c39
----- End Fatal Exception -------------------------------------------------
17-Dec-2018 13:05:11 CET  Closed file root://eospublic.cern.ch//eos/opendata/cms/MonteCarloUpgrade/RunIIAutumn18DR/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/GEN-SIM-RAW/PUAvg50IdealConditions_102X_upgrade2018_design_v9-v1/110000/09D95BE7-23C8-5542-9FA4-102E3FEDB7A2.root
```

(Note that I get the same error on lxplus). After some tests it's easy to find out that this error comes form the fact that I'm missing the era customisation (and then detector customisation).

`--era Run2_2018`

And adding it I have no issue on lxplus. On the contrary I get a new "DB" (l1 db) error on the VM

```
----- Begin Fatal Exception 17-Dec-2018 13:09:24 CET-----------------------
An exception of category 'Incomplete configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='l1conddb'
Exception Message:
Valid site-local-config not found at /cvmfs/cms.cern.ch/SITECONF/local/JobConfig/site-local-config.xml
----- End Fatal Exception -------------------------------------------------

```

I'm trying to track down where it pops up. I don't know if you have any suggestion.

**Comment by katilp** [comment]
Thanks: @ggovi Does this say something to you? Do we now have an additional db (in addition to the normal condition data) for l1?

**Comment by AdrianoDee** [comment]
@katilp Yes, is seems the case.

**Comment by katilp** [comment]
@AdrianoDee do you know if there's a newer GT with the required data already in?

**Comment by ggovi** [comment]
The line "Valid site-local-config not found at /cvmfs/cms.cern.ch/SITECONF/local/JobConfig/site-local-config.xml" should tell something.
It looks that some action in the workflow is still relying on frontier?

**Comment by AdrianoDee** [comment]
I think so, but I don’t know If there is a way to to avoid it. The Run2_2018 customisation seems to be the “problem” but it seems also to be necessary since the data (my deduction) have been generated with that era. I’m investigating.

**Comment by AdrianoDee** [comment]
**Step 2**

The issue with _l1conddb_ mentioned before may be solved in two steps.

1) Force the relative module ( _l1conddb_) to use the 102X_upgrade2018_design_v9 DB

```
myDb = cms.string('sqlite_file:/cvmfs/cms-opendata conddb.cern.ch/102X_upgrade2018_design_v9.db')
process.l1conddb.connect = myDb
```

2) This fix brings up a new error due to the fact that the naming of some tags in the the 102X_upgrade2018_design_v9 DB are different.

```
----- Begin Fatal Exception 29-Jan-2019 10:32:18 CET-----------------------
An exception of category 'ConditionDatabase' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='l1conddb'
Exception Message:
Tag "L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET" has not been found in the database. from IOVProxy::load 
----- End Fatal Exception -------------------------------------------------
```

This can be easily fixed by fixing the tag name in the configuration file taking it from the conddb ([here](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloParams_Stage2v3_2018_mc))

```
process.l1conddb.connect = myDb
process.l1conddb.toGet   = cms.VPSet(
            cms.PSet(
                 record = cms.string('L1TCaloParamsO2ORcd'),
                 tag = cms.string("L1TCaloParams_Stage2v3_2018_mc")
            )
       )
```

The same issue with _l1conddb_ appears with another module _l1ugmtdb_ and may be solved in the same way with the help of CondDB ([here](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonGlobalParams_Stage2v0_2018_mc)).

```
process.l1ugmtdb.connect = myDb
process.l1ugmtdb.toGet   = cms.VPSet(
            cms.PSet(
                 record = cms.string('L1TMuonGlobalParamsO2ORcd'),
                 tag = cms.string("L1TMuonGlobalParams_Stage2v0_2018_mc")
            )
       )
```

With this fixes the step2 runs smootly and thus the first part of the production for "Online" pixeles production.

**Step 3**

The step3 config file is customized as the step2 since it shows the same issues but hit a new similar error.

```
----- Begin Fatal Exception 29-Jan-2019 22:46:17 CET-----------------------
An exception of category 'Incomplete configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='loadRecoTauTagMVAsFromPrepDB'
Exception Message:
Valid site-local-config not found at /cvmfs/cms.cern.ch/SITECONF/local/JobConfig/site-local-config.xml
----- End Fatal Exception -------------------------------------------------
```

Thus following what done before the DB is forced via sqlite

```
process.GlobalTag.connect = myDb

process.GlobalTag.globaltag = '102X_upgrade2018_design_v9'
process.GlobalTag.snapshotTime = cms.string("9999-12-31 23:59:59.000")

process.l1conddb.connect = myDb
process.l1ugmtdb.connect = myDb
process.loadRecoTauTagMVAsFromPrepDB.connect = myDb
```

As above this bring a new error related to the Tag name

```
----- Begin Fatal Exception 29-Jan-2019 22:50:47 CET-----------------------
An exception of category 'ConditionDatabase' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='loadRecoTauTagMVAsFromPrepDB'
Exception Message:
Tag "RecoTauTag_againstMuonMVAv1" has not been found in the database. from IOVProxy::load 
----- End Fatal Exception -------------------------------------------------
```

Now, differently from above, this is not avoidable simply by fixing the name because in the 102X_upgrade2018_design_v9  DB neither the _tag name_ (RecoTauTag_againstMuonMVAv1) neither the relative _record_ (see [GBRWrapperRcd](https://cmssdt.cern.ch/dxr/CMSSW/source/RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py#370)) exist. Indeed, inspetting the CondDB [(here)](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/RecoTauTag_againstMuonMVAv1) object seems to be copied from an external DB that is not accessible from the OpenData VM

<img width="908" alt="image" src="https://user-images.githubusercontent.com/16901146/51943553-0dc0ce80-241a-11e9-827c-6100c2240044.png">

I tried to figure if there's any way to avoid this issue but it seems this DB is necessary.

**Comment by AdrianoDee** [comment]
Sincerly I have no clear idea. This record is called here

https://cmssdt.cern.ch/dxr/CMSSW/source/RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py

and the db it refers to comes from the frontier

`CondDBTauConnection = CondDB.clone( connect = cms.string( 'frontier://FrontierProd/CMS_CONDITIONS' ) )`

The idea it may come from an external db is suggested only by the result in CondDB, but I'm not even remotely an expert about these stuff.

**Comment by katilp** [comment]
@ggovi @jmduarte Can you help here? An external db which we just copy over if small (not ideal) or get it included in a new GT. As this is part of the normal reco step, the latter would be better. Thanks!

**Comment by jmduarte** [comment]
That tag is available in the Production (and Preparation) database, it's just not part of any GlobalTag apparently.

It's weird to me that such a tag would be needed in a real RECO job, but I don't know much about that tag.

To just export this, I just did this (following the tutorial https://indico.cern.ch/event/507993/contributions/2020446/attachments/1252208/1847694/talk4_-_hands_on_tutorial.pdf):

```
cmsrel CMSSW_10_2_5
cd CMSSW_10_2_5/src
cmsenv
# check that's it there
conddb list RecoTauTag_againstMuonMVAv1
# export it to a local sqlite file with the same tag name
conddb_import -c sqlite_file:recotautag.db -f frontier://PromptProd/CMS_CONDITIONS -i RecoTauTag_againstMuonMVAv1 -t RecoTauTag_againstMuonMVAv1 
# check it again in the new file
conddb --db  recotautag.db list RecoTauTag_againstMuonMVAv1
```

I put the file here: `/afs/cern.ch/user/w/woodson/public/recotautag.db`

Making a new GlobalTag with this tag included (as well as all the other changes you had to do by hand) seems like the best solution, but probably needs @ggovi's or another AlCaDB person's help.

Thanks,
Javier

**Comment by katilp** [comment]
Thanks @jmduarte !

**Comment by ggovi** [comment]
@jmduarte 
it looks correct except that it would be preferable to use 
conddb copy RecoTauTag_againstMuonMVAv1 --destdb recotautag.db
instead of conddb_import...
acutally in order to have a single file it could be even copied in the sqlite file containing the GT

**Comment by AdrianoDee** [comment]
Eureka!

Following the instructions from @jmduarte and @ggovi I created a separate db with all the RecoTauTag tags and everything the production whole wf is working smoothly now. I put the db here

`/afs/cern.ch/user/a/adiflori/public/`

It's about 4MB

**Comment by fwyzard** [comment]
Dear all,
as we discussed in various email threads, these data were produced mixing an "ideal" signal sample on top of a "realistic" pileup sample.

As this does not make sense, and mixes up conditions there were never supposed to work together, would it make sense to delte the sample and "unpublish" it from the open data repository ?

**Comment by fwyzard** [comment]
Wait - unless they were already replaced with the correct ones from #2520 ?

**Comment by fwyzard** [comment]
Indeed, looks iike they were replaced... sorry for the noise.

**Comment by katilp** [comment]
Closing as remaining issues followed in #2576 (FIXME for usage example in ML sample record) and #2589 (attach zipped github repository)
