### ISSUE TITLE
records: add `methodology.steps` for MC datasets

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2506]
Add `steps` to `methodology` field expressing generation information for MC datasets. Stems from https://github.com/cernopendata/opendata.cern.ch/issues/2465.

- [x] provide example (@tiborsimko) #2527 
- [x] amend data model (@mantasavas) #2529
- [x] amend mappings (@mantasavas)
- [x] amend fixtures (@mantasavas @okraskaj) #2544
- [x] amend display templates (@pamfilos) #2537

**Comment by tiborsimko** [comment]
MC 2011 are done via #2565

**Comment by tiborsimko** [comment]
All done.
