### ISSUE TITLE
Needed for Monday

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#258]
Needed for CMS testing which we announce on Monday:
- [x] remove the feedback button from the right (if it does not disappear on its own), we will use
  usability test form and opendata-support@cern.ch see #227 
- [x] The changes to the  entry page as suggested by @espacial in #218 
  (graphics, remove experiments name under Education and Research, make
  links under Education and Research more "link-like")
- [x] The changes to the education page (also in #218) @espacial
  - Introduction -> Experiments in the tab
  - remove primary datasets and validated run collections in the education page
  - bring small icons for event display and histogramming (and furthe resources) above
    the collection
- [x] Similar changes to the research page @espacial
  - Add icons (links) to Working environments and Getting started above the collection
  - have collections in a similar format than under education (inlude primary datasets)
  - [x] add a short introduction (cfr Education) @RaoOfPhysics  #257
- [x] Replace Lorem ipsum on research page with a short introduction text @RaoOfPhysics #256
- [x] the search is improved (now stable, when I click on the different collections), but still
  shows Showing records 1 to 0 out of 0 results.  when clicking on Search with the text "collection:CMS-  Derived-Datasets" in the text field. If this won't be in place, let me know so that we can include it to the announce

~~\- [ ] event previewer for the derived event display files: it still loads the same example event for all files. @tpmccauley @pamfilos : any news on that?~~ See #240 and #340
