### ISSUE TITLE
CMS running documentation to-do list for 2023-2024.

### ISSUE THREAD

**Issue by jmhogan** [cernopendata/opendata.cern.ch#3452]
CMS will do a big documentation update in Autumn '23 -- Winter '24. This encompasses pages on the Portal, the Open Data Guide, and public CMS TWikis

Open Data Portal pages
- [ ] [Guide to research use](https://opendata.cern.ch/docs/cms-guide-for-research): update format (mostly "exploring" sections) from years --> file types, adding 2015 MiniAOD.
- [ ] [Guide to trigger system](https://opendata.cern.ch/docs/cms-guide-trigger-system): update with clear methods of accessing trigger info in AOD, MiniAOD. 
- [ ] [Guide for event production](https://opendata.cern.ch/docs/cms-guide-event-production): broaden to include examples for MiniAOD production
- [ ] Getting Started pages:
   - [ ] Morph [2010](https://opendata.cern.ch/docs/cms-getting-started-2010), [2011-2012](https://opendata.cern.ch/docs/cms-getting-started-2011), and [2015](https://opendata.cern.ch/docs/cms-getting-started-2015) pages into a "Getting Started with CMS (AOD Data 2010-2012)(MiniAOD Data 2015-on)" (and adapt to future file types). Pages should include:
      - Docker container instructions for each year on the page, hopefully in tabs
      - Data contents and how to list them (differs by file type). Link to Open Data Guide
      - EDAnalyzer example (differs by file type)
      - POET example for filtering and analyzing (for AOD and MiniAOD pages, using relevant branches)
      - Links and references.  
   - [ ] Test POET 2011 branch with 2010 container and file to look for issues using this analyzer.
   - [ ] Get tab support or find another solution #3451 

Pages needing only link checks and small updates with any future releases: 
- [ ] https://opendata.cern.ch/docs/cms-guide-docker
- [ ] https://opendata.cern.ch/docs/about-cms
- [ ] https://opendata.cern.ch/docs/cms-guide-pileup-simulation

Duplicate records of documentation pages to remove after checking for any links that point to them:
- [ ] https://opendata.cern.ch/record/70 --> https://opendata.cern.ch/docs/cms-guide-pileup-simulation
- [ ] https://opendata.cern.ch/record/71 --> https://opendata.cern.ch/docs/cms-simulated-dataset-names
- [ ] https://opendata.cern.ch/docs/cms-guide-troubleshooting --> Make this point to the CMS Open Data Guide FAQ for easier maintenance.

CMS Open Data Guide pages
- [ ] https://github.com/cernopendata/cms-opendata-guide/issues/113

**Comment by katilp** [comment]
With NanoAOD being available, we could update the portal docker guide https://opendata.cern.ch/docs/cms-guide-docker to include instructions for the root/python container usage.

It could have separate sections similar to
[Available CMSSW container images](https://opendata.cern.ch/docs/cms-guide-docker#images)
[Fetch a CMSSW image and start a container](https://opendata.cern.ch/docs/cms-guide-docker#fetch-start)
